src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Cocur\Slugify\Slugify;


/**
 * @ORM\Entity(repositoryClass=RecipeRepository::class)
 * @Vich\Uploadable
 */
class Recipe
{

    const CAT = [
        0 => 'Entrées',
        1 => 'Plats',
        2 => 'Desserts',
        3 => 'Boissons'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="recipe", fileNameProperty="filename")
     */
    private $main_pic;

    /**
     * @ORM\Column(type="integer")
     */
    private $prep_time;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cook_time;

    /**
     * @ORM\Column(type="text")
     */
    private $stuff;

    /**
     * @ORM\OneToMany(targetEntity=Steps::class, mappedBy="recipe", orphanRemoval=true)
     */
    private $steps;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="recipes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="integer")
     */
    private $persons;

    /**
     * @ORM\Column(type="integer")
     */
    private $category;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->steps = new ArrayCollection();
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     */
    public function setFilename(?string $filename): void
    {
        $this->filename = $filename;
    }

    /**
     * @return File|null
     */
    public function getMainPic(): ?File
    {
        return $this->main_pic;
    }

    /**
     * @param File|null $main_pic
     */
    public function setMainPic(?File $main_pic): Recipe
    {
        $this->main_pic = $main_pic;
        if ($main_pic) {
            $this->updated_at = new \DateTime();
        }
        return $this;
    }



    public function getPrepTime(): ?int
    {
        return $this->prep_time;
    }

    public function setPrepTime(int $prep_time): self
    {
        $this->prep_time = $prep_time;

        return $this;
    }

    public function getCookTime(): ?int
    {
        return $this->cook_time;
    }

    public function setCookTime(?int $cook_time): self
    {
        $this->cook_time = $cook_time;

        return $this;
    }

    public function getStuff(): ?string
    {
        return $this->stuff;
    }

    public function setStuff(string $stuff): self
    {
        $this->stuff = $stuff;

        return $this;
    }

    /**
     * @return Collection|Steps[]
     */
    public function getSteps(): Collection
    {
        return $this->steps;
    }

    public function addStep(Steps $step): self
    {
        if (!$this->steps->contains($step)) {
            $this->steps[] = $step;
            $step->setRecipe($this);
        }

        return $this;
    }

    public function removeStep(Steps $step): self
    {
        if ($this->steps->contains($step)) {
            $this->steps->removeElement($step);
            // set the owning side to null (unless already changed)
            if ($step->getRecipe() === $this) {
                $step->setRecipe(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param mixed $category
     * @return Recipe
     */
    public function setCategory($category)
    {
        $this->category = $category;
        return $this;
    }

    public function getCatStr() {
        return self::CAT[$this->category];
    }

    public function getNbSteps(): int
    {
        return count($this->steps);
    }

    public function getSlug(): string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->title);
    }

    public function getPersons(): ?int
    {
        return $this->persons;
    }

    public function setPersons(int $persons): self
    {
        $this->persons = $persons;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Recipe;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        foreach (Recipe::CAT as $k => $v) {
            $choices[$v] = $k;
        }

        $builder
            ->add('title', TextType::class, [
                'label' => false
            ])
            ->add('category', ChoiceType::class, [
                'label' => false,
                'choices' => $choices
            ])
            ->add('description', TextType::class, [
                'label' => false
            ])
            ->add('main_pic', FileType::class, [
                'label' => false
            ])
            ->add('prep_time', IntegerType::class, [
                'label' => false
            ])
            ->add('cook_time', IntegerType::class, [
                'label' => false
            ])
            ->add('persons', IntegerType::class, [
                'label' => false
            ])
            ->add('stuff', CKEditorType::class, [
                'label' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use App\Form\RecipeEditType;
use App\Form\RecipeType;
use App\Repository\RecipeRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RecipeController extends AbstractController {

    /**
     * @var RecipeRepository
     */
    private $repository;
    /**
     * @var EntityManagerInterface
     */
    private $em;
    /**
     * @var UserRepository
     */
    private $uRepo;


    public function __construct(RecipeRepository $repository, EntityManagerInterface $em, UserRepository $uRepo)
    {
        $this->repository = $repository;
        $this->em = $em;
        $this->uRepo = $uRepo;
    }

    /**
     * @return Response
     * @Route("/create/recipe", name="recipe.create")
     */
    public function create(Request $request): Response
    {
        $recipe = new Recipe();
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        $user = $this->uRepo->findBy(['id' => $this->getUser()->getId()]);

        if($form->isSubmitted() && $form->isValid()) {
            $recipe->setAuthor($user[0]);
            $this->em->persist($recipe);
            $this->em->flush();

            $this->addFlash('success', 'Recette créée avec succès');
            return $this->redirectToRoute('steps.create', [
                'recipe_id' => $recipe->getId()
            ]);
        }

        return $this->render('recipe/create.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView()
        ]);
    }

    /**
     * @return Response
     * @Route("/recipe/{slug}-{id}", name="recipe.show", requirements={"slug": "[a-z0-9\-]*"})
     */
    public function show(Recipe $recipe, string $slug): Response
    {
        if($recipe->getSlug() !== $slug) {
            return $this->redirectToRoute('recipe.show', [
                'id' => $recipe->getId(),
                'slug' => $recipe->getSlug()
            ], 301);
        }

        return $this->render('recipe/show.html.twig', [
            'recipe' => $recipe,
            'current_menu' => 'last',
            'steps' => $recipe->getSteps()
        ]);
    }

    /**
     * @return Response
     * @Route("/recipe/category/{cat_id}", name="recipe.category")
     */
    public function category($cat_id): Response
    {
        $recipes = $this->repository->findBy([
            'category' => $cat_id
        ]);
        return $this->render('recipe/list.html.twig', [
            'recipes' => $recipes,
            'cat' => Recipe::CAT[$cat_id]
        ]);
    }

    /**
     * @return Response
     * @Route("/edit/recipe/{recipe_id}", name="recipe.edit")
     * @ParamConverter("recipe", options={"mapping": {"recipe_id"   : "id"}})
     */
    public function edit(Request $request, Recipe $recipe): Response
    {
        $form = $this->createForm(RecipeEditType::class, $recipe);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($recipe);
            $this->em->flush();

            $this->addFlash('success', 'Recette modifiée avec succès');
            return $this->redirectToRoute('recipe.show', [
                'id' => $recipe->getId(),
                'slug' => $recipe->getSlug()
            ]);
        }

        return $this->render('recipe/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView()
        ]);
    }
}

templates/recipe/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid mt-5">
        <div class="col-md-8 mx-auto pt-5">
            {{ form_start(form) }}
            <div class="col">
                <div class="form-group">
                    <label>Titre</label>
                    {{ form_row(form.title) }}
                </div>

                <div class="form-group">
                    <label>Categorie</label>
                    {{ form_row(form.category) }}
                </div>

                <div class="form-group">
                    <label>Description</label>
                    {{ form_row(form.description) }}
                </div>
            </div>

            <div class="col d-flex flex-column flex-md-row justify-content-between">
                <div class="col-12 col-md-5 p-0">
                    <div class="form-group">
                        <label>Image</label>
                        {{ form_row(form.main_pic) }}
                    </div>

                    <div class="form-group">
                        <label>Nombre de personnes</label>
                        {{ form_row(form.persons) }}
                    </div>
                </div>

                <div class="col-12 col-md-5 p-0">

                    <div class="form-group">
                        <label>Temps de préparation (Minutes)</label>
                        {{ form_row(form.prep_time) }}
                    </div>

                    <div class="form-group">
                        <label>Temps de cuisson (Minutes)</label>
                        {{ form_row(form.cook_time) }}
                    </div>
                </div>
            </div>


            <div class="col">
                <div class="form-group">
                    <label>Ingredients</label>
                    {{ form_row(form.stuff) }}
                </div>

                <div class="form-group">
                    <button class="btn btn-light-green">Étape suivante</button>
                </div>
            </div>

            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block title 'Nouveau post'%}

templates/recipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid mt-5">
        <div class="col-md-8 mx-auto pt-5">
            {{ form_start(form) }}
            <div class="col">
                <div class="form-group">
                    <label>Titre</label>
                    {{ form_row(form.title) }}
                </div>

                <div class="form-group">
                    <label>Categorie</label>
                    {{ form_row(form.category) }}
                </div>

                <div class="form-group">
                    <label>Description</label>
                    {{ form_row(form.description) }}
                </div>
            </div>

            <div class="col d-flex flex-row justify-content-between">
                <div class="col-12 col-md-5 p-0">
                    <div class="form-group">
                        <label>Image</label>
                        {{ form_row(form.main_pic) }}
                    </div>

                    <div class="form-group">
                        <label>Nombre de personnes</label>
                        {{ form_row(form.persons) }}
                    </div>
                </div>

                <div class="col-12 col-md-5 p-0">

                    <div class="form-group">
                        <label>Temps de préparation (Minutes)</label>
                        {{ form_row(form.prep_time) }}
                    </div>

                    <div class="form-group">
                        <label>Temps de cuisson (Minutes)</label>
                        {{ form_row(form.cook_time) }}
                    </div>
                </div>
            </div>


            <div class="col">
                <div class="form-group">
                    <label>Ingredients</label>
                    {{ form_row(form.stuff) }}
                </div>

                <div class="form-group">
                    <button class="btn btn-light-green">Enregistrer</button>
                </div>
            </div>

            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block title 'Nouveau post'%}

templates/recipe/list.html.twig
{% extends 'base.html.twig' %}

{% block title cat %}

{% block body %}

    <div class="container-fluid d-flex flex-column justify-content-center align-items-center mt-5">
        <h1 class="mt-5">{{ cat }}</h1>
        <div class="row flex-wrap col-md-12">
            {% for recipe in recipes %}
                <div class="card col-md-2 p-0">
                    <img class="card-img-top" src="/images/recipe/{{ recipe.filename }}" alt="Card image cap">
                    <div class="card-body">
                        <h4 class="card-title"><a>{{ recipe.title }}</a></h4>
                        <p class="card-text">{{ recipe.description }}</p>
                        <a href="{{ path('recipe.show', {id: recipe.id, slug: recipe.slug}) }}" class="btn btn-light-green">Voir</a>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}

templates/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title recipe.title %}

{% block head %}
    <meta property="og:url" content="https://recettes.mamawdev.fr/index.php/recipe/{{ recipe.slug }}-{{ recipe.id }}" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Recettes" />
    <meta property="og:description" content="{{ recipe.description }}" />
    <meta property="og:image" content="https://recettes.mamawdev.fr/index.php/public/images/recipe/{{ recipe.filename }}" />
{% endblock %}

{% block body %}
<div class="container-fluid mt-5">
    <div class="col-md-12 mx-auto p-0 recipe-show pt-5">

        <h1 class="recipe-title text-center">{{ recipe.title }}</h1>

        <div class="col-md-12 d-flex flex-column flex-md-row">

            <div class="recipe-left-head d-flex flex-md-column col-12 col-md-6">
                <div class="recipe-img-container">
                    <img class="recipe-img mx-auto" src="/images/recipe/{{ recipe.filename }}" alt="{{ recipe.title }}">
                </div>
            </div>

            <div class="recipe-right-head d-flex flex-column col-12 col-md-6 my-3 my-md-0">

                <div class="recipe-stuff">
                    <h3 class="text-center">Ingredients</h3>
                    {% autoescape %}
                        {{ recipe.stuff|raw }}
                    {% endautoescape %}
                </div>

                <div class="recipe-badge">
                    <div class="col-md-12 d-flex">
                        <div class="col-md-6">
                            <span class="badge badge-pill light-green d-flex col-md-4"><i class="fas fa-users fa-2x" aria-hidden="true"></i><p class="m-auto">{{ recipe.persons }}</p></span>
                            <span class="badge badge-pill light-green d-flex col-md-4 mt-1"><i class="fas fa-utensils fa-2x"></i><p class="m-auto">{{ recipe.prepTime }} min.</p></span>
                            <span class="badge badge-pill light-green d-flex col-md-4 mt-1"><i class="fas fa-temperature-high fa-2x"></i><p class="m-auto">{{ recipe.cookTime }} min.</p></span>
                        </div>
                        <div class="col-md-6">
                            <span id="fb-share" class="badge badge-pill badge-share facebook light-blue d-flex col-md-4"><i class="fab fa-facebook fa-2x"></i><p class="m-auto">Partager</p></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="recipe-desc-container my-5">
            <h3 class="text-center">{{ recipe.description }}</h3>
        </div>

        {% for step in steps %}
            <div class="row d-flex flex-column flex-md-row mt-5 col-md-10 step-show p-0 mx-auto">
                <img class="steps-img" src="/images/recipe/{{ step.filename }}">
                <div class="col p-4">
                    <h3>{{ step.title }}</h3>
                    <p>{{ step.content }}</p>
                    {% if app.user is same as (recipe.author) %}
                    <a href="{{ path('steps.edit', {step_id: step.id}) }}" class="btn btn-light-green">Modifier</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block javascripts %}
    <script>
        document.getElementById('fb-share').onclick = function() {
            FB.ui({
                display: 'popup',
                method: 'share',
                href: 'https://recettes.mamawdev.fr{{ path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) }}',
            }, function(response){});
        }
    </script>
{% endblock %}